spring.application.name=saboresdelnorte
server.port=8089
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=sabores_del_norte;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Password123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
ws.security.username=usr_admin
ws.security.password=pwd_admin